# Generated by Django 2.2 on 2019-10-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='other_image1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='other_image2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='other_image3',
        ),
    ]
