# Generated by Django 2.2 on 2019-10-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191024_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='other_image',
            field=models.ImageField(default='./media_root/1318-600x0.jpg', upload_to=''),
        ),
    ]
