# Generated by Django 2.2 on 2019-10-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_other_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='other_image2',
            field=models.ImageField(default='./media_root/1318-600x0.jpg', upload_to=''),
        ),
    ]
