# Generated by Django 2.2 on 2019-10-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_other_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='other_image2',
        ),
        migrations.AlterField(
            model_name='item',
            name='other_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
