# Generated by Django 2.2 on 2019-10-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191024_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='other_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
