# Generated by Django 2.2 on 2019-10-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191024_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='other_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
