# Generated by Django 2.2 on 2019-10-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191025_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='other_image',
        ),
    ]
