# Generated by Django 2.2 on 2019-10-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191025_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='other_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default="This product don't have any description"),
        ),
    ]
