# Generated by Django 2.2 on 2019-10-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191025_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='other_image',
        ),
    ]
