# Generated by Django 2.2 on 2019-10-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191025_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='img5',
        ),
    ]
