from django.urls import path
from .views import (ItemListView,
                    HomeView,
                    OrderDetailView,
                    OrderListView,
                    PaymentDetailView,
                    PaymentListView,
                    CheckoutView,
                    shop,
                    success_send,
                    about,
                    faq,
                    contact,
                    OrderSummaryView,
                    FavView,
                    fav_update,
                    ItemDetailView,
                    men_category_view,
                    women_category_view,
                    add_to_cart,
                    AddCouponView,
                    remove_from_cart,
                    remove_single_item_from_cart,
                    PaymentView,
                    RequestRefundView,
                    ItemCreateView,
                    ItemDeleteView,
                    ItemUpdateView,
                    dashboard,
                    OrderCreateView,
                    OrderUpdateView,
                    OrderDeleteView,
                    PaymentCreateView,
                    PaymentUpdateView,
                    PaymentDeleteView,
                    CouponCreateView,
                    CouponUpdateView,
                    CouponDeleteView,
                    CouponListView,
                    RefundCreateView,
                    RefundUpdateView,
                    RefundDeleteView,
                    RefundListView,
                    RefundDetailView,
                    AddressCreateView,
                    AddressUpdateView,
                    AddressDeleteView,
                    AddressListView,
                    AddressDetailView,
                    )
app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('all-items/', ItemListView.as_view(), name='all-items'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('all-orders/', OrderListView.as_view(), name='all-orders'),
    path('payment/<int:pk>/', PaymentDetailView.as_view(), name='pay-detail'),
    path('all-payments/', PaymentListView.as_view(), name='all-payments'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('shop/', shop, name='shop'),
    path('success_send/', success_send, name='success_send'),
    path('about/', about, name='about'),
    path('faq/', faq, name='faq'),
    path('contact/', contact, name='contact'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('favorites/', FavView, name='fav'),
    path('favorites/<slug>/', fav_update, name='fav_update'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('boys/', men_category_view, name='men'),
    path('girls/', women_category_view, name='women'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('item/new/', ItemCreateView.as_view(), name='item-create'),
    path('item/<int:pk>/delete/', ItemDeleteView.as_view(), name='item-delete'),
    path('item/<int:pk>/update/', ItemUpdateView.as_view(), name='item-update'),
    path('dashboard/', dashboard, name="dashboard"),
    path('order/new/', OrderCreateView.as_view(), name='order-create'),
    path('order/<int:pk>/update/', OrderUpdateView.as_view(), name='order-update'),
    path('order/<int:pk>/delete/', OrderDeleteView.as_view(), name='order-delete'),
    path('payment/new/', PaymentCreateView.as_view(), name='payment-create'),
    path('payment/<int:pk>/update/',
         PaymentUpdateView.as_view(), name='payment-update'),
    path('payment/<int:pk>/delete/',
         PaymentDeleteView.as_view(), name='payment-delete'),
    path('coupon/new/', CouponCreateView.as_view(), name='coupon-create'),
    path('coupon/<int:pk>/update/',
         CouponUpdateView.as_view(), name='coupon-update'),
    path('coupon/<int:pk>/delete/',
         CouponDeleteView.as_view(), name='coupon-delete'),
    path('all-coupons/', CouponListView.as_view(), name='coupons'),
    path('refund/new/', RefundCreateView.as_view(), name='refund-create'),
    path('refund/<int:pk>/update/',
         RefundUpdateView.as_view(), name='refund-update'),
    path('refund/<int:pk>/delete/',
         RefundDeleteView.as_view(), name='refund-delete'),
    path('all-refunds/', RefundListView.as_view(), name='refunds'),
    path('refund/<int:pk>/', RefundDetailView.as_view(), name='refund-detail'),

    path('address/new/', AddressCreateView.as_view(), name='address-create'),
    path('address/<int:pk>/update/',
         AddressUpdateView.as_view(), name='address-update'),
    path('address/<int:pk>/delete/',
         AddressDeleteView.as_view(), name='address-delete'),
    path('all-address/', AddressListView.as_view(), name='address'),
    path('address/<int:pk>/', AddressDetailView.as_view(), name='address-detail'),

]
